filecoin-project/go-fil-markets

shared/tokenamount/tokenamount.go, shared/tokenamount/tokenamount_test.go
fix all naming in token amount file and add explanatory comments
=> fix(tokenamount): fix naming

.circleci/config.yml, datatransfer/README.md
The datatransfer README ToC links were bad.  This fixes them.
=> fix links in datatransfer README

filestore/filestore.go
Some minors while reading this pkg, most relevant:
- ~~use `filepath` to rely on stdlib~~
- since `Store` codeflow is simple enough, we can avoid defer to go the extra mile to see if closing fails.
=> filestore: use filepath pkg, track close err, lints

pieceio/mocks/PieceIO.go, pieceio/pieceio.go, pieceio/pieceio_test.go, pieceio/types.go, storagemarket/impl/client.go, storagemarket/impl/client_utils.go
Use PieceIO and CAR file to generate CommP.
Resolves https://github.com/filecoin-project/go-storage-market/issues/13
=> Use CAR file in generation of CommP

retrievalmarket/network/libp2p_impl_test.go
This test is flaky; it passed a lot in the PR branch and flakes now that it's in master.  This obviously causes problems for others.
Skip it while I work on it in a branch.
=> skip flaky test

retrievalmarket/network/libp2p_impl_test.go
=> Flaky test fix

codecov.yml
The project shows as failing cause of codecov... it likely will be for several months till the test coverage is up. In the meantime, let's take a slightly less agreesive approach of tracking code coverage, displaying as a report in PRs, but not breaking the build on it.
=> ci(codecov): disable status, display report

retrievalmarket/impl/client.go, retrievalmarket/impl/provider.go
add a mutex to protect access in the retrieval market to the subscriber list
(per changes in LOTUS PR within repo)
=> fix(retrievalmarket): add mutex around subscribers

retrievalmarket/impl/client.go, retrievalmarket/impl/provider.go
In order to get the retrieval market PR merged, LOTUS asked us to add a mutex around the subscriber list, which we did
=> lotus branch merge back

pieceio/pieceio.go, pieceio/pieceio_test.go, pieceio/types.go, storagemarket/impl/client.go, storagemarket/impl/client_utils.go, storagemarket/impl/provider.go, storagemarket/impl/provider_states.go, storagemarket/impl/provider_utils.go, storagemarket/types.go
The Provider now writes out a padded CAR file of the graph fetched from the client.  It uses this file to calculate `CommP` and verify that it matches the `CommP` in the proposal.  It then saves the path to this file in the `MinerDeal`, so the node can pass this information on to the mining/binpacking module.
Resolves https://github.com/filecoin-project/go-storage-market/issues/15
=> Use CAR and padding for piece data

storagemarket/impl/client.go, storagemarket/impl/client_states.go, storagemarket/impl/provider.go, storagemarket/impl/provider_states.go, storagemarket/impl/provider_utils.go, storagemarket/impl/request_validation_test.go, storagemarket/impl/types.go, storagemarket/types.go
Rename `DealState` to `StorageDealStatus`, add the states from the spec, and map them as closely as possible to the old `DealState` enum.
There are some unused states, and the provider and client states are not broken up according to the states in the spec (leaving some unused states).  This will be addressed when we figure out what is going on with the state machines for the client and provider deals.
Resolves https://github.com/filecoin-project/go-storage-market/issues/21
=> Sync up DealState to match spec

.circleci/config.yml
We are getting OOM errors while linking on CI, so let's try switching to the large resource class for now
=> ci(config): use large resource_class

go.mod, retrievalmarket/discovery/local.go, retrievalmarket/impl/client.go, retrievalmarket/impl/client_test.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_test.go, retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/providerstates/provider_states_test.go, retrievalmarket/network/libp2p_impl_test.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, shared_testutil/test_types.go, shared_testutil/testutil.go
To support both Lotus and GFC integration, we are switching away from using pieceCIDs for retrieval.
This PR changes the names and types on the expected interfaces, thought importantly, it leaves the implementation the same under the hood (treating payloadCIDs as if they were pieceCIDs). The fix to actually implement PayloadCID based retrieval will come in the next PR.
=> Switch interfaces for retrieval to use Payload CIDs. NO IMPLEMENTATION

go.mod, go.sum, piecestore/piecestore.go, piecestore/piecestore_test.go, piecestore/types.go, piecestore/types_cbor_gen.go, retrievalmarket/discovery/local.go, retrievalmarket/impl/blockunsealing/blockunsealing.go, retrievalmarket/impl/blockunsealing/blockunsealing_test.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_test.go, retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/providerstates/provider_states_test.go, shared_testutil/test_piecestore.go, storagemarket/impl/provider_states.go
Allow Retrieval deals to work with actual Payload CIDs
-- add a second mapping to the PieceStore that translates from a CID to pieces its a part of
-- support unsealling pieces from CIDs as needed (theoretically a dag could span multiple pieces in the future where pieces are not whole dags -- not super important though)
-- add very preliminary writes of CID -> Piece mapping on storage provider side
--- IMPORTANT: Not included is mapping any CIDs in the IPLD graph other than the root to Piece, or recording where in the piece blocks actually live. This can definitely be done by recording this information as we write the CAR file. This is definitely temporary implementation meant to get us to working retrieval by payload CID fast, with allowing retrievals based off of CIDs deeper in the dag …
=> Properly Implement Retrieval Lookups Based on CIDs

storagemarket/impl/client_states.go, storagemarket/impl/provider_states.go, storagemarket/types.go
Move the point at which the sector id is passed from the node to the storage market.  It is now communicated via the `DealSectorCommittedCallback`.
Resolves https://github.com/filecoin-project/go-storage-market/issues/22
=> Handle sector id in the `OnDealSectorCommitted` callback

storagemarket/impl/provider.go
`storageimpl.NewProvider` errors out when it is given a datastore that does not contain a 'miner-address' value. This is not documented and also not a great way to pass configuration around between components.
Make `minerAddress` a parameter to `NewProvider` so we do not need to retrieve it from the datastore.
=> take miner address as parameter

go.mod, go.sum, pieceio/pieceio.go, pieceio/types.go, storagemarket/impl/client.go, storagemarket/impl/client_utils.go, storagemarket/integration_test.go, storagemarket/types.go
We updated our internal types, but some of our dependencies updated as well -- this updates to use the go-sectorbuilder that uses specs-actors types
Update -- FFI, go-sectorbuilder, & go-padreader
Also use abi.UnpaddedPieceSize where appropriate, and make appropriate conversion in deal PieceSize calculation
=> Update go-sectorbuilder to latest that uses specs-actors types

go.mod, go.sum, retrievalmarket/impl/clientstates/client_states_test.go, retrievalmarket/impl/testnodes/test_retrieval_client_node.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, shared_testutil/test_types.go
The latest specs-actors has the changes to paych.Actor that I introduced in [specs-actors PR #157](https://github.com/filecoin-project/specs-actors/pull/157), which makes Lane and Nonce `Uint64s`. In going back to retrieval market implementation I saw that go-fil-markets hasn't yet updated to the latest specs-actors.  This is blocking me, since my branch is up-to-date with go-filecoin master, which itself uses the latest specs-actors, and now I am seeing test failures which can't be resolved without this update.
Update to latest specs-actors and fix the problems that arise:  int64 --> uint64 and rerun cbor-gen.
=> Use latest specs-actors with uint64 lane and nonce from paych.Actor

go.mod, go.sum, retrievalmarket/impl/blockunsealing/blockunsealing.go, retrievalmarket/impl/client.go, retrievalmarket/impl/client_test.go, retrievalmarket/impl/clientstates/client_fsm.go, retrievalmarket/impl/clientstates/client_states.go, retrievalmarket/impl/clientstates/client_states_test.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_test.go, retrievalmarket/impl/providerstates/provider_fsm.go, retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/providerstates/provider_states_test.go, retrievalmarket/network/deal_stream.go, retrievalmarket/network/network.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, shared_testutil/mocknet.go, shared_testutil/test_network_types.go
- persist retrieval deals on both client and provider
- remove common logic around transitioning states to make code more readable
- make it simply to decouple steps in retrieval market to enable easier resuming of state (not in this PR but coming soon)
- Use go-statemachine and the FSM module defined in this PR https://github.com/filecoin-project/go-statemachine/pull/4
- Define the state machine's event logic in a single place, separate from the state handlers -- see `provider_fsm.go` & `client_fsm.go`
- Simplify state handlers that no longer have to modify state but just dispatch events
- Update provider & client to construct statemachines from a data store so they are saved on disk
- Dispatch several new more informative events for different things that can happen in a retrieval deal
- …
=> Use go-statemachine + FSMs in retrieval market

retrievalmarket/impl/client.go, retrievalmarket/impl/client_test.go, retrievalmarket/impl/integration_test.go, shared_testutil/mocknet.go, storedcounter/storedcounter.go, storedcounter/storedcounter_test.go
Make retrieval deal id incrementing survive restarts so they can serve as unique deal ids for a single retrieval client (fix #66 )
- Create a simple stored counter interface that saves an incrementing counter on top of a data store
- Use it in retrieval market
- The integration test recreates all the test data on each retrieval and therefore does not test the counter -- should it?
- This should go in after #124 cause it's on top of it (I currently set that branch as the base)
=> Persist retrieval market counter to disk

shared_testutil/test_types.go
In the latest specs-actors, which go-filecoin is using, `paych.SignedVoucher` does not have a `Timelock` field. This was causing tests in my go-filecoin branch to fail. Since we don't use the field in testing anyway in go-fil-markets, I have deleted the line that uses it in `MakeTestSignedVoucher`, which also removes the need to use another version of specs-actors in stable.
=> One line change: do not initialize test SignedVoucher with Timelock field

retrievalmarket/impl/client.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, storagemarket/impl/client.go, storagemarket/impl/client_cbor_gen.go, storagemarket/impl/provider_states.go, storagemarket/integration_test.go, storagemarket/types.go
When trying to ensure funds for a miner, we were just adding funds to the worker key, which doesnt really help much (its not associated with the miner on chain in that way). Switching that over, things then tried to send money from the miner actor, which obviously doesnt work, so now we pass the address you want to ensure has funds on the market, and the address to send funds from.
=> allow specification of 'wallet' for ensure funds calls

retrievalmarket/impl/provider.go, retrievalmarket/impl/testnodes/test_retrieval_provider_node.go, retrievalmarket/types.go
In order to setup payment channel, we need to return the actual address of the wallet for the miner in response to queries, not just the storage miner actors address
Add a node method similar to the one on StorageProviderNode to look up the wallet address, translate that address when responding to queries
=> feat(retrievalmarket): support wallet address

retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/providerstates/provider_states_test.go
Allow self-deal retrievals to complete
In the case of retrieving data that one stored with one's own storage mining node, the wallet addresses are the same, and payment vouchers are already saved. As a result, saving the payment voucher succeeds but returns a value of 0 for the delta between the voucher and the last voucher saved. In this case, we can fall back to examining the actual voucher amount and subtracting from the funds received to verify the actual delta. This allows retrieval deals to complete.
This has actually been broken for some time, but it only became apparent when a recent change to the retrieval market forced the client to actually confirm it's last payment was accepted -- prior to that tests passed in Lotus even though the deal actually failed, cause the client …
=> Handle self-retrieval correctly

storagemarket/impl/client.go, storagemarket/impl/client_utils.go, storagemarket/types.go
This is needed for the offline deal flow
=> allow manual piece commitment

storagemarket/types_cbor_gen.go
Just reruns cbor-gen -- looks like it did not get run when we added PieceCid & PieceSize to DataRef
=> fix(cborgen): update cbor gen for dataref

go.mod, go.sum
We want to get the newest version of libfilecoin into go-filecoin, and that requires an upgrade to go-fil-markets (to take newest filecoin-ffi and go-sectorbuilder).
=> upgrade to libfilecoin version that supports cache clearing

codecov.yml
We should not be tracking coverage on CBOR gen files
=> ci(codecov): ignore cbor gen files

retrievalmarket/impl/testnodes/test_retrieval_provider_node.go, retrievalmarket/types.go, shared/types.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
This PR makes incremental progress towards [completing this ZenHub issue](https://app.zenhub.com/workspaces/markets-shared-components-5daa144a7046a60001c6e253/issues/filecoin-project/go-fil-markets/148).
When a provider or client needs information from the chain, they need to provide a chain state identifier to which their query is scoped. Due to potential reorgs, chain height does not serve as identity for a tipset.
This PR changes the signature and name of the existing chain state identity-acquiring method, and adds that method to all `*Node` interfaces which query for (or will query for, in the short future) chain state.
=> add TipSet identity-producing method to various Node interfaces

retrievalmarket/impl/provider.go, retrievalmarket/impl/testnodes/test_retrieval_provider_node.go, retrievalmarket/types.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerutils/providerutils.go, storagemarket/impl/providerutils/providerutils_test.go, storagemarket/impl/storedask/storedask.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
Makes incremental progress towards https://github.com/filecoin-project/go-fil-markets/issues/148.
=> send state identifiery when getting miner worker address

retrievalmarket/impl/clientstates/client_states.go, retrievalmarket/impl/testnodes/test_retrieval_client_node.go, retrievalmarket/types.go
This PR makes incremental progress towards the larger goal of providing a tipset identifier to the node to which it scopes all chain queries.
=> retrieval client node interface passes tipset identifier to node

retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/testnodes/test_retrieval_provider_node.go, retrievalmarket/types.go
Implementations of the `SavePaymentVoucher` will need to inspect payment channel actor state in order to load the payment channel parties. It has historically used the chain head (implicitly) but should accept a tipset identifier.
=> Add TipSetToken to SavePaymentVoucher

go.mod, go.sum
This changeset updates filecoin-ffi and go-sectorbuilder to use the latest (v24) Groth parameters.
=> v24 groth parameters

Makefile, go.mod, go.sum, storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerutils/providerutils.go, storagemarket/impl/providerutils/providerutils_test.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
This is the last (hopefully) PR in a chain of PRs which pass chain state identifiers to methods on the `Node*` interfaces.
=> send tipset identifier to node when interacting with chain

storagemarket/impl/client.go, storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/types.go
Closes #173, Cleanup: Rename ListInProgressDeals, ListIncompleteDeals to ListLocalDeals
> Rename StorageClient.ListInProgressDeals -> StorageClient.ListLocalDeals
> Rename StorageProvider.ListIncompleteDeals -> StorageProvider.ListLocalDeals
> Change in implementations and get tests passing as needed
=> rename list deals interface & impls

storagemarket/impl/clientutils/clientutils.go, storagemarket/integration_test.go, storagemarket/types.go
With these changes, the offline deal workflow succeeds
=> Improve offline deals

storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/cliest_states_test.go
=> For a storage deal proposal that is rejected, include rejection reason in client response

piecestore/types_cbor_gen.go, retrievalmarket/impl/blockunsealing/blockunsealing.go, retrievalmarket/impl/blockunsealing/blockunsealing_test.go, retrievalmarket/impl/provider.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, retrievalmarket/types_test.go, shared_testutil/test_piecestore.go, storagemarket/impl/blockrecorder/blockrecorder_cbor_gen.go, storagemarket/network/types_cbor_gen.go, storagemarket/types_cbor_gen.go
Add a `PieceCid` field to the block unsealer struct, which will restrict which piece it will try to unseal from.
Resolves #179
=> Support specifying PieceCID in retrievals

retrievalmarket/common.go, retrievalmarket/impl/client.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, shared_testutil/mocknet.go
Closes #170 
* Decode selector in client.Receive and if valid, pass to the block SelectorVerifier
* Decode selector when creating a new provider, and if valid, pass to the SelctorBlockReader
* Add 2 unit tests, one that uses the allselector and one that selects some
=> Support selectors on retrieval

storagemarket/impl/client.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go, storagemarket/integration_test.go, storagemarket/types.go
We should probably put something in that ensures that the new max piece size is less than or equal to the sector size.
This PR also includes a commit that makes the Storage Market client refuse to propose a deal if piece size > sector size.
=> Add a max piece size to storage asks

go.mod, retrievalmarket/discovery/local.go, retrievalmarket/discovery/local_test.go
Closes #101 
Amend storage record of payloadCIDs to  store a list of retrieval peers instead of just one.
=> add multiple peers per payloadCID

CHANGELOG.md, CONTRIBUTING.md
Document our release process going forward. We will go with `master` always being the latest tagged release, and `development` being our default branch.
- update CONTRIBUTING.md with release process
- create an initial CHANGELOG.md
Once this merges I will make changes to project settings so `development` is the default branch.
=> Document release process and create initial change log

go.mod, go.sum
Please lmk - or just rebase this - if this should target another branch. Impls wish to consume this immediately, without needing to consume any markets API or functionality changes.
=> Upgrade to specs-actors v0.3.0

CONTRIBUTING.md
Per @icorderi, @anorth, @whyrusleeping, this updates our release process to use master as the main branch for ongoing development (stable in the sense it must pass tests but not in the sense of being released). 
- Update Contributing.MD with new development and release process details
=> New release process

storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/network/libp2p_impl.go, storagemarket/network/network.go
Fix a bug in lotus where ListLocalDeals fails across the process boundary due to JSON marshalling error
- Set the local miner peer id on MinerDeal 
- Verify JSON marshall/unmarshal works
fixes #209
=> fix(storagemarket): set miner peer id on deals

shared_testutil/test_ipld_tree.go, storagemarket/impl/client.go, storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/types.go
Add pubSub/SubscribeToEvents to StorageDeal Client, similarly to StorageDeal Provider
Closes #213
=> ppl can sub to storage client evts

go.mod, go.sum, retrievalmarket/discovery/local.go, storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
Get the latest go-fil-markets integrated with lotus so we can cut a 0.2.0 branch
The integration revealed we can't as it turns out, wait with confidence on a chain message, only a state change -- we could technically call StateGetReceipt or StateSearchMessage -- but this would likely be extremely slow :(
So, in the absence, I removed confidence for now. 
Also, our callback takes an exit code and data, but does not account for the possibility that the wait call itself errors (i.e. message was never posted). So I added third error parameter to the callback to capture this.
I also added a context to the call (LOTUS and I imagine GFC API expect a context), and made a few dependency updates
=> Storage Market Changes Based On Lotus Integration

.circleci/config.yml
Adds a cbor-gen check to CI config, which runs cbor-gen-for and errors if there are any diffs afterward.  Closes #231
=> Feat/cbor gen check ci #231

shared_testutil/test_network_types.go, storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/network/deal_stream.go, storagemarket/network/libp2p_impl.go, storagemarket/network/network.go
Don't drop open storage deal connections
Libp2p's connection manager supports a tagging functionality which helps prevent connections from getting cleaned up when there are lots of them active.
This PR adds a method to do this to the storage deal stream, then pipes it through to the storage deal process so connections get tagged at the moment they become likely to stay open a long time and then untagged at close.
Unfortunately, libp2p's mock network has a connection manager that does nothing, so it's hard to test this at an actual integration level :(
=> Tag deal connections to preserve them

storagemarket/impl/client.go, storagemarket/impl/provider.go
Unbuffered channels in the top-level functions `AddPaymentEscrow` and `AddStorageCollateral` can deadlock if the implementation of `WaitForMessage` is synchronous.
Make channels have a buffer.
=> Buffer the done channel when adding storage collateral

storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/requestvalidation/request_validation_test.go, storagemarket/impl/requestvalidation/unified_request_validator.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
So far:
- fix an issue where we attempt to close a stream we never opened if funds are not ensured
- update the universal request validator to support different stores for push + pull, make this the way of detecting if we accept pushes/pulls (if store = nil)
Need:
More fixes?
~~Tests for fix to close stream issue~~
=> Fixes from filecoin integration work

storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_fsm.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/integration_test.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
Provides same functionality as #260 but with setting up deal decision logic as a custom option on the provider interface, rather than altering the node interface, understanding this may be something that miners customize on an individual level
- Use commits from #260
- Remove custom decider from node interface
- Setup custom decider as a StorageProviderOption
- Add tests to verify state changes
=> Deal Decision Custom Function

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/provider.go, storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go, storagemarket/integration_test.go
Add one more element of datastore customization
- Move stored ask out of provider so its setup and configured seperately. 
- Also allow customizing the DS key for stored ask
- Remove prefix for provider in DS store
- Modify integration tests
=> Remove storedask from provider

retrievalmarket/storage_retrieval_integration_test.go, shared_testutil/test_types.go, shared_testutil/testutil.go, storagemarket/impl/client.go, storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/dtutils/dtutils.go, storagemarket/impl/dtutils/dtutils_test.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_fsm.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/impl/providerutils/providerutils.go, storagemarket/impl/providerutils/providerutils_test.go, storagemarket/integration_test.go, storagemarket/types.go
Switch piece data transfer to a client push.
resolves #192
=> Tentative acceptance protocol

README.md, filestore/README.md, pieceio/README.md, piecestore/README.md, piecestore/piecestore.go, piecestore/types.go, retrievalmarket/README.md, retrievalmarket/types.go, storagemarket/README.md, storagemarket/impl/provider.go
Documentation pass for modules in this repo. 
* Add README.md to root of each package, filestore, pieceio, piecestore, retrievalmarket, and storagemarket
* Link to READMEs on main README
* Write interface implementation documentation for storagemarket and retrievalmarket
* Write a little bit about filestore, pieceio, and piecestore. 
I would appreciate feedback or even better,  more detailed content on the storagemarket module since I don't know it as well as retrieval.
=> Feat/module docs #83

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/provider.go, storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go, storagemarket/integration_test.go, storagemarket/types.go
Searching for a `DeleteAsk` operation caused me to go down the rabbit hole of trying to figure out how asks added with the `AddAsk` method could be replaced with a new ask (when the miner changed their minimum piece size, for instance). 
As it turns out, the current implementation of go-fil-markets allows a storage miner to have exactly one ask, manipulated through the misleadingly-named `AddAsk` method.
This PR replaces the `AddAsk` method with a `SetAsk` method, and replaces `ListAsks` with `GetAsk`.
If a `SignedStorageAsk` had an identity (I don't see that it does right now), we could preserve the `AddAsk` and `ListAsks` signatures. We'd need to add a `DeleteAsk` method, though.
=> replace AddAsk with SetAsk, to convey intent

storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go
Store more detailed information in the client's local state when a deal is rejected.  Specifically, store the message given by the StorageProvider, if any.
=> Store more detailed information in ClientDealState when a deal is rejected

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/integration_test.go, storagemarket/testnodes/testnodes.go
Provide a real response to GetMinerInfo so that integration tests pass
=> fix(storagemarket): fix integration test harness

go.mod, retrievalmarket/storage_retrieval_integration_test.go, storagemarket/README.md, storagemarket/impl/client.go, storagemarket/integration_test.go, storagemarket/network/libp2p_impl.go, storagemarket/network/network.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
Not quite complete as i havent gotten the tests to pass yet, but this is most of the work.
=> use addresses from miner info for connecting to miners

storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/integration_test.go, storagemarket/network/libp2p_impl.go, storagemarket/network/types.go, storagemarket/network/types_cbor_gen.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
Send the fast retrieval flag along with the proposal and track it in the `ClientDeal` and `MinerDeal`.  Also return this flag in the deal status query.
Resolves #285
=> Fast retrieval support

storagemarket/impl/client.go, storagemarket/impl/provider.go
Deal restarts make take a while particularly if there are connection timeouts. There's no reason to
run them synchronously in node initialization, and we definitely should not fail node startup if there are errors.
Run restart deals in a go routine, simply log any errors
=> Run deal restarts in go routine

storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
For verified deal proposals, reject the deal if the `verifreg.DataCap` for the client isn't large enough.
Resolves #286
=> Validate client's DataCap for verified deals

retrievalmarket/impl/client.go
=> add locks around client deals in retrieval market

retrievalmarket/network/libp2p_impl_test.go, retrievalmarket/types.go
Add a new retrievalmarket function, `NewQueryV1`, which takes an optional `PieceCID`.
Resolves #287
=> Support PieceCIDs in retrieval queries

storagemarket/impl/provider.go, storagemarket/impl/provider_test.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go
Subsumed by https://github.com/filecoin-project/lotus/pull/2384
=> Include chain height when running custom decision logic

storagemarket/impl/client.go
Without this, deals fail unless the client is using the default wallet address.
=> Use client address, not default address, to sign proposals

storagemarket/impl/client.go, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go
Per https://docs.google.com/document/d/1cyO_Ah0R9XbfgpR_isJUtEREspbco_A6EDYJZWouR-8/edit# -- we are encoding the payload CID in the Label field on deals to enable discoverability.
Encode a JSON structure into the label field (tried CBOR, but issue arise from the fact that label is a string). Matches label described in doc but with proper IPLD DAG JSON CID structure.
=> Add label field to deals

shared_testutil/test_network_types.go, storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/network/deal_stream.go, storagemarket/network/libp2p_impl.go, storagemarket/network/network.go
Resolve: https://github.com/filecoin-project/go-fil-markets/issues/361
This is believe it or not just a rebase of @ingar's PR from a bit back with a few updates -- mainly putting connection tagging around the whole deal rather than just the data transfer.
=> Add back connection tagging

go.mod, go.sum, retrievalmarket/types_cbor_gen.go, shared_testutil/generators.go, storagemarket/network/types_cbor_gen.go, storagemarket/types_cbor_gen.go
Depends on https://github.com/filecoin-project/go-data-transfer/pull/64.
=> Update specs-actors and cbor-gen

storagemarket/impl/client.go
If the `ProviderCollateral` value is provided in the `ProposeStorageDealParams`, we should use it (if not, estimate it using `DealProviderCollateralBounds as before).
=> Use collateral from ProposeStorageDealParams

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/client.go, storagemarket/impl/client_environments.go, storagemarket/impl/provider.go, storagemarket/impl/provider_environments.go, storagemarket/impl/requestvalidation/common.go, storagemarket/impl/requestvalidation/request_validation_test.go, storagemarket/impl/requestvalidation/unified_request_validator.go, storagemarket/integration_test.go
Fix a race condition where deal status in request validation could fall behind actual events dispatched (resulting in state = StorageDealAcceptWait when Get was called, which then caused a deal rejection)
- Move registering of voucher types for storage market into storage market constructor (long holdover of original way markets was extracted from lotus)
- Use an interface to abstract how deals are "gotten" from the store in Request Validator
- Provide implementation of said interface for client and provider (still assumes multi-process model with seperate data transfer -- we'll need to think about what we want to do if this ever goes back in go-filecoin)
- Register storage voucher types in constructors for client and provider
- Move all of these little "environment wrappers" -- …
=> Use GetSync in Request Validation

go.mod, go.sum, piecestore/types_cbor_gen.go, retrievalmarket/discovery/local_cbor_gen.go, retrievalmarket/types_cbor_gen.go, storagemarket/impl/client.go, storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/network/types_cbor_gen.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
should help us close https://github.com/filecoin-project/lotus/issues/2646
=> add deal creation time to deals

README.md
Merge once all the issues are moved to lotus and the issues feature is disabled.
=> docs: Add disclaimer to guide people to report issues in Lotus

Makefile, go.mod, go.sum, retrievalmarket/impl/integration_test.go, retrievalmarket/network/libp2p_impl.go, retrievalmarket/types.go, storagemarket/integration_test.go, storagemarket/network/libp2p_impl.go, storagemarket/network/libp2p_impl_test.go
Closes https://github.com/filecoin-project/lotus/issues/3416.
@hannahhoward Should we do this for the retrieval market as well ?
=> Retry with exponential backoff for stream opening

storagemarket/integration_test.go
TestMakeDealOffline was hanging due to provider not starting
=> Fix test hang

go.mod, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go
Shorten the label field by using CBOR
Use CBOR instead of json (previously was using different options with JSON encoder to avoid whitespace)
=> Convert label JSON to CBOR

go.mod, storagemarket/impl/client.go, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go
Because of issues with encoding the CID in a CBOR struct inside a string field for label, but also not wanting to pad things out with JSON, we're switching to encoding the CID directly as Multibase string.
- Write label field as a multibase string 
- Use base58 for Cid V0 (only one supported)
- Use base64 for Cid V1 (base32 is default but we're trying to keep things more compact)
=> Encode cid directly in label field rather than try to use structured data

storagemarket/impl/client.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_fsm.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
The cid of a message can change when published to the chain because of gas fee changes.  Since the Provider passes a cid back to the client when queried for deal status, it could send the incorrect cid back to the client, causing the client to fail to verify the published deal.
Store the actual/final cid in the `MinerDeal`
This is the market-side fix for https://github.com/filecoin-project/lotus/issues/3703
=> Store final/actual cid for publish message

storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/testnodes/testnodes.go
Closes https://github.com/filecoin-project/lotus/issues/3443.
Also, downgrades stream reset log in `HandleDealStatusStream` to `WARN` instead of `ERROR`.
=> Test Restart for ClientEventDealPublished AND ClientEventDealActivated

retrievalmarket/impl/integration_test.go, retrievalmarket/network/libp2p_impl.go, retrievalmarket/network/libp2p_impl_test.go, retrievalmarket/storage_retrieval_integration_test.go, storagemarket/integration_test.go, storagemarket/network/libp2p_impl.go, storagemarket/network/libp2p_impl_test.go
- Remove need to for further PRs to change network retry parameters by making them a configuration option
- Make tests run quickly again
- add the var args config option pattern to the Libp2p impls for storage and retrieval market networks
- add an options to change all the retry parameters
- set parameters to avoid retries in relevant tests
=> Configurable Retry Parameters (to speedup tests)

retrievalmarket/impl/client.go, retrievalmarket/impl/provider.go, retrievalmarket/types.go
Just some minor typos in comments :)
=> Tidy up comments

retrievalmarket/defaults.go, retrievalmarket/impl/askstore/askstore_impl.go, retrievalmarket/impl/askstore/askstore_impl_test.go, retrievalmarket/impl/provider.go, retrievalmarket/provider.go, storagemarket/impl/storedask/storedask.go
Create a retrievalmarket `AskStore` interface and implementation, which will persist the retrieval ask to disk so that the configuration will persist through restarts.  This is modeled after the storagemarket's `StoredAsk`.
Resolves filecoin-project/lotus/issues/3907
=> Persist retrieval ask on disk

storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go
Previously, we weren't including the client collateral when considering storage deal proposals; it was assumed it was always 0.
Use `ClientBalanceRequirement()` when verifying client funds, which includes the client collateral.
Resolves filecoin-project/lotus/issues/3864
=> Consider ClientCollateral when validating deal proposal

storagemarket/README.md, storagemarket/client.go, storagemarket/impl/client.go, storagemarket/impl/provider.go, storagemarket/nodes.go, storagemarket/provider.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
We have these two methods that have never made any sense to me and I think are not used -- basically -- they just call the node, then return the values back. It seems like it makes way more sense for these methods to just live on the node itself, if they're neccesary (I think they're not in use FWIW). This also removes any reference to market actor existing deal state, which is important for the purposes of the actors upgrade.
Remove the methods, node adapter methods, and unused types
=> Remove passthrough methods

shared_testutil/testutil.go, storagemarket/impl/provider.go, storagemarket/impl/provider_test.go
There is an edge case in the deal flow where a client sends the deal proposal and shuts down for some reason.  When the client restarts, it resends the deal proposal, but the provider has already started tracking the deal, and rejects the proposal.
There is no problem with re-sending the deal response, and not changing anything in the provider state.  This will allow the deal to continue on the client's state machine.
Resolves part of https://github.com/filecoin-project/lotus/issues/3966
=> Handle re-sent deal proposals

storagemarket/integration_test.go
Fix this particular flaky test by providing a specific event to stop the provider at, rather than stopping the provider when the client event is hit.
There is still a slim edge case here, if the provider shuts down after a FSM event is emitted and before the state transition happens.  However, this edge case, while rare in actual usage, is one that affects all events and will have to be addressed in the FSM.
See https://github.com/filecoin-project/lotus/issues/3966
=> Fix flaky TestRestartClient/ClientEventDataTransferComplete

storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go
For https://github.com/filecoin-project/lotus/issues/4220
=> Correct behaviour for `SetAsk`

storagemarket/impl/clientstates/client_states.go
For legacy deals in transferring state, we did not record the restart ID for the transfer so we can't restart them. So we need to fail the deal.
Right now we are just trying to restart anyway which causes a nil panic -- eek!
=> Fix panil on transfer id not present

storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go
If `SetAsk()` is called without a parameter to configure `MaxPieceSize`, it will revert to the default value.
If a previously-stored ask is available, use its `MaxPieceSize` as a default, like is done for `MinPieceSize`
=> Preserve MaxPieceSize when calling SetAsk

storagemarket/impl/providerstates/provider_fsm.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go
Analysis of code indicates one possible way for stray temp files to be left hanging around is when commP's do not match. In this case, temporary piece files are generated but not recorded on the deal, and are therefore not cleaned up in the StorageDealFailing state.
Save the piecePath and filestorePath when commP does not match so that the files get deleted
=> Remove temp files

storagemarket/impl/clientstates/client_states.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
Add PublishCID parameter to OnDealSectorCommitted so that function can account for DealID changes
Change method signature, add params
=> Pass PublishCID

CHANGELOG.md
Integrate new lotus FundManager
- [Integrate new FundManager](https://github.com/filecoin-project/go-fil-markets/pull/445)
| Dirk McCormick | 1 | +75/-311 | 17 |
=> release: v1.0.4

storagemarket/integration_test.go
We have several tests that use waitgroup.Wait(), which can lock up the test until it hits the generic test timeout.
This change makes waitgroup.Wait() respect the context.
=> Fail fast in tests that use a waitgroup Wait()

CHANGELOG.md
- Remove temp files (#449) ([filecoin-project/go-fil-markets#449](https://github.com/filecoin-project/go-fil-markets/pull/449))
- fix: fail fast in tests that use a waitgroup Wait() (#450) ([filecoin-project/go-fil-markets#450](https://github.com/filecoin-project/go-fil-markets/pull/450))
- Make it possible to configure the proof type at runtime. ([filecoin-project/go-fil-markets#448](https://github.com/filecoin-project/go-fil-markets/pull/448))
Contributors
| Hannah Howard | 1 | +292/-393 | 17 |
| Steven Allen | 1 | +21/-11 | 6 |
| dirkmc | 1 | +21/-7 | 1 |
=> release: v1.0.5

storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go
To provide more visibility when negotiating deals, store the provider's deal state in the local `ClientDeal` when waiting for deal acceptance.
Resolves https://github.com/filecoin-project/lotus/issues/5062
=> Store provider state when polling for acceptance

CHANGELOG.md
- feat: go-data-transfer 1.2.2 (#459) ([filecoin-project/go-fil-markets#459](https://github.com/filecoin-project/go-fil-markets/pull/459))
- Cancel transfer should cause Storage deal to fail (#457) ([filecoin-project/go-fil-markets#457](https://github.com/filecoin-project/go-fil-markets/pull/457))
- Give more visibility (to the client) while waiting for deal acceptance (#458) ([filecoin-project/go-fil-markets#458](https://github.com/filecoin-project/go-fil-markets/pull/458))
- docs(CHANGELOG): update for v1.0.7 release ([filecoin-project/go-fil-markets#456](https://github.com/filecoin-project/go-fil-markets/pull/456))
- github.com/filecoin-project/go-data-transfer (v1.0.1 -> v1.2.2):
- fix(graphsync): fix UseStore for restarts (#115) …
=> release: v1.0.8

storagemarket/impl/clientstates/client_fsm.go
When a deal has been accepted we should clear the deal message.
Otherwise it will still say something like "Provider state: StorageDealVerifyData"
=> clear deal message when deal accepted

CHANGELOG.md
Generating Changelog for github.com/filecoin-project/go-fil-markets v1.0.9..73534649f61b89d2a332b0939e19aa440a9dc6dc
- feat: update to go-data-transfer v1.2.3 (#465) ([filecoin-project/go-fil-markets#465](https://github.com/filecoin-project/go-fil-markets/pull/465))
- Normalize final states for cancelled retrieval deals (#464) ([filecoin-project/go-fil-markets#464](https://github.com/filecoin-project/go-fil-markets/pull/464))
- github.com/filecoin-project/go-data-transfer (v1.2.2 -> v1.2.3):
- Better retry config (#124) ([filecoin-project/go-data-transfer#124](https://github.com/filecoin-project/go-data-transfer/pull/124))
- feat: expose channel state on Manager interface (#125) ([filecoin-project/go-data-transfer#125](https://github.com/fileco …
=> release: v1.0.10

CHANGELOG.md
When the miner restarts it should not dial the client, the client will automatically dial the miner.
- on restart miner shouldn't dial client (#463) ([filecoin-project/go-fil-markets#463](https://github.com/filecoin-project/go-fil-markets/pull/463))
- github.com/filecoin-project/go-data-transfer (v1.2.3 -> v1.2.4):
- Automatically restart push channel (#127) ([filecoin-project/go-data-transfer#127](https://github.com/filecoin-project/go-data-transfer/pull/127))
- github.com/ipfs/go-graphsync (v0.5.0 -> v0.5.2):
- RegisterNetworkErrorListener should fire when there's an error connecting to the peer (#127) ([ipfs/go-graphsync#127](https://github.com/ipfs/go-graphsync/pull/127))
- Permit multiple data subscriptions per original topic (#128) …
=> release: v1.0.11

CHANGELOG.md
Better retry config
- feat: retry config - separate max open attempts from backoff factor (#467) ([filecoin-project/go-fil-markets#467](https://github.com/filecoin-project/go-fil-markets/pull/467))
Contributors
| dirkmc | 2 | +236/-113 | 12 |
=> release: v1.1.0

CHANGELOG.md
- feat: go-data-transfer v1.2.5 (with restart limit) (#470) ([filecoin-project/go-fil-markets#470](https://github.com/filecoin-project/go-fil-markets/pull/470))
- github.com/filecoin-project/go-data-transfer (v1.2.4 -> v1.2.5):
- feat: limit consecutive restarts with no data transfer (#129) ([filecoin-project/go-data-transfer#129](https://github.com/filecoin-project/go-data-transfer/pull/129))
Contributors
| dirkmc | 4 | +212/-82 | 9 |
| Dirk McCormick | 1 | +13/-0 | 1 |
=> release: v1.1.1

CHANGELOG.md
Generating Changelog for github.com/filecoin-project/go-fil-markets v1.1.1..d43e9447747b51824c9628e7cff5f2d2c97ae253
- feat: update to go-data-transfer v1.2.7 (#472) ([filecoin-project/go-fil-markets#472](https://github.com/filecoin-project/go-fil-markets/pull/472))
- github.com/filecoin-project/go-data-transfer (v1.2.5 -> v1.2.7):
- feat: configurable send message timeouts (#136) ([filecoin-project/go-data-transfer#136](https://github.com/filecoin-project/go-data-transfer/pull/136))
- log request / response events (#137) ([filecoin-project/go-data-transfer#137](https://github.com/filecoin-project/go-data-transfer/pull/137))
- fix: dont complete transfer because graphsync request was cancelled (#134) …
=> release: v1.1.2

CHANGELOG.md
- fix: handle retrieval deals with zero price per byte (#477) ([filecoin-project/go-fil-markets#477](https://github.com/filecoin-project/go-fil-markets/pull/477))
Contributors
| dirkmc | 2 | +144/-28 | 13 |
=> release: v1.1.3

CHANGELOG.md
- retrieval: skip payment channel creation if total price is zero (#480) ([filecoin-project/go-fil-markets#480](https://github.com/filecoin-project/go-fil-markets/pull/480))
Contributors
| dirkmc | 1 | +36/-7 | 8 |
=> release: v1.1.5

storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
Now that deals are published with more than one deal ID, move parsing of the publish message response into lotus rather than doing it in markets.
=> Move publish deals msg response parsing from markets into lotus

CHANGELOG.md
- fix: move publish deals msg response parsing from markets into lotus (#475) ([filecoin-project/go-fil-markets#475](https://github.com/filecoin-project/go-fil-markets/pull/475))
Contributors
| dirkmc | 2 | +60/-22 | 5 |
=> release: v1.1.6

storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go
Addresses https://github.com/filecoin-project/lotus/issues/5516
=> Better storage fsm error handling

CHANGELOG.md
- Better storage fsm error handling (#484) ([filecoin-project/go-fil-markets#484](https://github.com/filecoin-project/go-fil-markets/pull/484))
- release: v1.1.6 (#485) ([filecoin-project/go-fil-markets#485](https://github.com/filecoin-project/go-fil-markets/pull/485))
Contributors
| dirkmc | 2 | +91/-20 | 3 |
=> release: v1.1.7

CHANGELOG.md
- feat: add RawBlockSize to DataRef (#487) ([filecoin-project/go-fil-markets#487](https://github.com/filecoin-project/go-fil-markets/pull/487))
Contributors
| dirkmc | 2 | +47/-3 | 3 |
=> release: v1.1.8

storagemarket/impl/client.go
This was a poor bit of UX that required users to multiply their storage price by the padded size of their data in order to propose the correct thing to the miner.
price should always be specified in the same terms. Miners asks say price in FIL/GB/Epoch, and what the user types should match this.
=> price specification by user should match what miner has in their ask

discovery/migrations/migrations_cbor_gen.go, discovery/types_cbor_gen.go, go.mod, go.sum, piecestore/migrations/migrations_cbor_gen.go, piecestore/types_cbor_gen.go, retrievalmarket/migrations/migrations_cbor_gen.go, retrievalmarket/types_cbor_gen.go, storagemarket/impl/blockrecorder/blockrecorder_cbor_gen.go, storagemarket/impl/requestvalidation/types_cbor_gen.go, storagemarket/migrations/migrations_cbor_gen.go, storagemarket/network/types_cbor_gen.go, storagemarket/types_cbor_gen.go
(https://github.com/whyrusleeping/cbor-gen/pull/50)
=> Update cbor-gen to ingore unknown map fields

CHANGELOG.md
- Update cbor-gen to ingore unknown map fields (#492) ([filecoin-project/go-fil-markets#492](https://github.com/filecoin-project/go-fil-markets/pull/492))
Contributors
| Łukasz Magiera | 1 | +111/-33 | 13 |
| Dirk McCormick | 1 | +1/-3 | 1 |
=> release: v1.1.9

retrievalmarket/impl/provider_environments.go, retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/migrations/migrations_test.go, retrievalmarket/testing/test_provider_deal_environment.go
There seems to be an issue where the error message when unsealing fails is getting swallowed: https://github.com/filecoin-project/lotus/issues/5829
To make sure any read errors are surfaced, this PR explicitly closes the reader after reading the the unsealed data into the blockstore and returns any error.
=> close the reader after unsealing into blockstore

storagemarket/impl/clientstates/client_fsm.go, storagemarket/integration_test.go
Verifies that when the connection goes down then is restored during a transfer, the deal completes successfully.
This test has surfaced the following issue:
https://github.com/filecoin-project/go-data-transfer/issues/153
Once that issue has been resolved, the test can be merged.
=> Add TestBounceConnectionDataTransfer

CHANGELOG.md
- feat: update to go-data-transfer v1.2.9 (#508) (#504) ([filecoin-project/go-fil-markets#504](https://github.com/filecoin-project/go-fil-markets/pull/504))
- always try to return some message to the client (#498) ([filecoin-project/go-fil-markets#498](https://github.com/filecoin-project/go-fil-markets/pull/498))
- fix: close the reader after unsealing into blockstore (#507) ([filecoin-project/go-fil-markets#507](https://github.com/filecoin-project/go-fil-markets/pull/507))
- fix: disallow concurrent retrieval deals for same peer/cid (#493) ([filecoin-project/go-fil-markets#493](https://github.com/filecoin-project/go-fil-markets/pull/493))
- make deal state channel id nilable (#490) ([filecoin-project/go-fil-markets#490](https://github.com/file …
=> release: v1.2.0

CHANGELOG.md
- feat: update tests for go-data-transfer 1.3.0 (#510) ([filecoin-project/go-fil-markets#510](https://github.com/filecoin-project/go-fil-markets/pull/510))
- github.com/filecoin-project/go-data-transfer (v1.2.9 -> v1.3.0):
- feat: use random number instead of incrementing counter for transfer ID (#169) ([filecoin-project/go-data-transfer#169](https://github.com/filecoin-project/go-data-transfer/pull/169))
Contributors
| dirkmc | 4 | +185/-95 | 21 |
| Dirk McCormick | 1 | +11/-0 | 1 |
=> release: v1.2.1

CHANGELOG.md
- feat: update to go-data-transfer v1.4.0 (#514) ([filecoin-project/go-fil-markets#514](https://github.com/filecoin-project/go-fil-markets/pull/514))
- github.com/filecoin-project/go-data-transfer (v1.3.0 -> v1.4.0):
- feat: add config options to enable / disable push or pull monitoring individually (#174) ([filecoin-project/go-data-transfer#174](https://github.com/filecoin-project/go-data-transfer/pull/174))
- fix: ensure channel monitor shuts down when transfer complete (#171) ([filecoin-project/go-data-transfer#171](https://github.com/filecoin-project/go-data-transfer/pull/171))
Contributors
| dirkmc | 5 | +65/-17 | 9 |
| Dirk McCormick | …
=> release: v1.2.2

storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go
Closes https://github.com/filecoin-project/go-fil-markets/issues/503.
=> Poll Provider for acceptance only till (deal start epoch + grace period) has elapsed 

CHANGELOG.md
- feat: update to go-data-transfer v1.4.1 (#523) ([filecoin-project/go-fil-markets#523](https://github.com/filecoin-project/go-fil-markets/pull/523))
- Poll Provider for acceptance only till (deal start epoch + grace period) has elapsed  (#516) ([filecoin-project/go-fil-markets#516](https://github.com/filecoin-project/go-fil-markets/pull/516))
- Add DealStages to track and log Deal status updates (#502) ([filecoin-project/go-fil-markets#502](https://github.com/filecoin-project/go-fil-markets/pull/502))
- github.com/filecoin-project/go-data-transfer (v1.4.0 -> v1.4.1):
- Add ChannelStages to keep track of history of lifecycle of a DataTransfer (#163) ([filecoin-project/go-data-transfer#163](https://github.com/filecoin-project/go-data-transfer/pu …
=> release: v1.2.4

go.mod, retrievalmarket/impl/client.go, retrievalmarket/impl/client_test.go, retrievalmarket/impl/integration_test.go, retrievalmarket/storage_retrieval_integration_test.go, shared/timecounter.go, shared/timecounter_test.go, shared_testutil/mocknet.go
Fixes https://github.com/filecoin-project/go-fil-markets/issues/519
Currently the ID used for a retrieval deal is a counter that increments starting from zero. The counter is stored in state, so if the state is wiped out, the counter restarts from zero.
This can cause issues when for example a client wipes their state, but the provider still has state about deals with IDs 0 - 10. The client's deals will fail until their deal ID counter rises above 10.
This PR changes the retrieval deal ID to be based on the current time, so that it will not repeat if the client's state is wiped.
=> Retrieval: use time-based deal ID instead of stored counter

CHANGELOG.md
- add timeout for sending cancel message to peer when retrieval cancelled (#531) ([filecoin-project/go-fil-markets#531](https://github.com/filecoin-project/go-fil-markets/pull/531))
- Flush out & fix retrieval bugs (#525) ([filecoin-project/go-fil-markets#525](https://github.com/filecoin-project/go-fil-markets/pull/525))
- fix: use time-based deal ID instead of stored counter (#529) ([filecoin-project/go-fil-markets#529](https://github.com/filecoin-project/go-fil-markets/pull/529))
- github.com/filecoin-project/go-data-transfer (v1.4.1 -> v1.4.2):
- Support no-op error responses  (#186) ([filecoin-project/go-data-transfer#186](https://github.com/filecoin-project/go-data-transfer/pull/186))
- fix: fail a pull channel when there is a timeout …
=> release: 1.2.5-rc2

CHANGELOG.md
- fix restarts during data transfer for a retrieval deal (#540) ([filecoin-project/go-fil-markets#540](https://github.com/filecoin-project/go-fil-markets/pull/540))
- Test Retrieval for offline deals (#541) ([filecoin-project/go-fil-markets#541](https://github.com/filecoin-project/go-fil-markets/pull/541))
- Allow anonymous submodule checkout (#535) ([filecoin-project/go-fil-markets#535](https://github.com/filecoin-project/go-fil-markets/pull/535))
- github.com/filecoin-project/go-data-transfer (v1.4.3 -> v1.5.0):
- Add isRestart param to validators (#197) ([filecoin-project/go-data-transfer#197](https://github.com/filecoin-project/go-data-transfer/pull/197))
- fix: flaky TestChannelMonitorAutoRestart (#198) …
=> release: v1.3.0

Makefile
Clone and first make all report error:
```sh
➜  go-fil-markets git:(fix-makefile) make all
/Library/Developer/CommandLineTools/usr/bin/make -C ./extern/filecoin-ffi/ .install-filcrypto
make[1]: *** No rule to make target `.install-filcrypto'.  Stop.
make: *** [.filecoin-build] Error 2
```
=> fix first make error

go.mod, go.sum, retrievalmarket/impl/clientstates/client_states.go, retrievalmarket/impl/dtutils/dtutils.go, retrievalmarket/impl/integration_test.go, retrievalmarket/retrieval_restart_integration_test.go, retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/dtutils/dtutils.go, storagemarket/integration_test.go
Update to go data transfer v1.6.0 and fix [voucher accounting issue](https://github.com/filecoin-project/lotus/issues/6297)
=> Update to go data transfer v1.6.0

storagemarket/impl/requestvalidation/common.go, storagemarket/impl/requestvalidation/request_validation_test.go
We should not have this check, restricting data transfer to only the specific peer who made the deal cuts out a lot of potential architectures (and is silly anyways given the ephemeral nature of libp2p peer IDs). Knowledge of the proposal CID and the miners desire of the data being pushed in the first place should be validation enough.
=> remove wrong peer check in push deal validation

storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
The deal ID may change if there is a reorg after the deal publish message lands on chain, so pass the deal proposal instead
=> Pass deal proposal instead of deal ID to OnDealExpiredOrSlashed

CHANGELOG.md
- Pass deal proposal instead of deal ID to OnDealExpiredOrSlashed (#476) ([filecoin-project/go-fil-markets#476](https://github.com/filecoin-project/go-fil-markets/pull/476))
=> release: 1.7.0

storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
This reverts commit 2e06ce3307ed3a7c23f4abba907d7020c1f732e7.
I wrote up a quick test (possibly buggy) on the Lotus side (see https://github.com/filecoin-project/lotus/pull/5431#issuecomment-899768787), and unfortunately it didn't produce the results I expected.
Given that this is on master and we need to make a release to get the dagstore changes out, I had two options:
1. Merge the lotus change anyway without tests -- which made me feel uneasy.
2. Back out this change from master and make a 1.8.0 release this module without it.
I'm sad to choose 2, but I prefer for something to stay broken in master for a few more days, than to possibly introduce other unintended side-effects.
=> Revert "refactor: pass deal proposal instead of deal ID to OnDealExpiredOrSlashed (#476)"

go.mod, go.sum, retrievalmarket/impl/client_test.go, retrievalmarket/impl/provider_test.go, retrievalmarket/migrations/maptypes/maptypes.go, retrievalmarket/migrations/maptypes/maptypes_cbor_gen.go, retrievalmarket/migrations/migrations.go, retrievalmarket/migrations/migrations_cbor_gen.go, retrievalmarket/migrations/migrations_test.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, storagemarket/impl/client_test.go, storagemarket/impl/provider_test.go, storagemarket/migrations/migrations.go, storagemarket/migrations/migrations_cbor_gen.go
Farewell! Following the adoption of the dagstore, this library is no longer used.
`StoreID` fields have been kept for backwards compatibility and reset to uint64 (which should serialize identically to multistore.StoreID) but they're really unused.
=> rm go-multistore dependency.

CHANGELOG.md
- Remove go-multistore dependency
- update go-data-transfer to v1.9.0
- Revert "Pass deal proposal instead of deal ID to OnDealExpiredOrSlashed (#476) ([filecoin-project/go-fil-markets#476](https://github.com/filecoin-project/go-fil-markets/pull/476))"
=> release: v1.11.0

CHANGELOG.md
Reinstate update to graphsync v0.9.0 with new Linksystem IPLD prime
=> release: v1.12.0

go.mod, go.sum, retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/client.go, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go, storagemarket/integration_test.go
Limit the depth of a DAG we're willing to process for CommP, expose this as
a configurable option via the public API.
Blockers:
=> Expose MaxTraversalLinks option for generating CommP

CHANGELOG.md
- commp: expose MaxTraversalLinks option for generating CommP (#633) ([filecoin-project/go-fil-markets#633](https://github.com/filecoin-project/go-fil-markets/pull/633))
- fix: retrieval not found error (#630) ([filecoin-project/go-fil-markets#630](https://github.com/filecoin-project/go-fil-markets/pull/630))
- github.com/filecoin-project/go-data-transfer (v1.10.0 -> v1.11.0):
- feat: update to go-ipld-prime v0.12.3 (#261) ([filecoin-project/go-data-transfer#261](https://github.com/filecoin-project/go-data-transfer/pull/261))
- refactor: remove libp2p protocol cache (#259) ([filecoin-project/go-data-transfer#259](https://github.com/filecoin-project/go-data-transfer/pull/259))
- feat: update to graphsync v0.10.0-rc3 (#258) …
=> release: v1.13.0

CHANGELOG.md
- feat: upgrade to go-data-transfer v1.11.1 (#636) ([filecoin-project/go-fil-markets#636](https://github.com/filecoin-project/go-fil-markets/pull/636))
- github.com/filecoin-project/go-data-transfer (v1.11.0 -> v1.11.1):
- feat: update to go-graphsync v0.10.0 (#263) ([filecoin-project/go-data-transfer#263](https://github.com/filecoin-project/go-data-transfer/pull/263))
- github.com/ipfs/go-graphsync (v0.10.0-rc3 -> v0.10.0):
- feat: update to go-ipld-prime v0.12.3 (#237) ([ipfs/go-graphsync#237](https://github.com/ipfs/go-graphsync/pull/237))
Contributors
| Dirk McCormick | 2 | +33/-0 | 2 |
| dirkmc | 3 | +14/-16 | 7 |
=> release: v1.13.1

go.mod, go.sum, stores/filestore.go, stores/kvcarbs.go
This PR updates go-car to v2.1.0, and fixes compat with the filestore car(ish) index in the least hacky way per Slack discussion.
=> Update go-car to v2.1.0 

README.md
The prior link forwarded correctly from the gh pages link to spec.filecoin.io, but did not land the user at the correct section.
=> Fix and de-duplicate link to spec

shared/commp.go, storagemarket/impl/provider.go, storagemarket/impl/provider_environments.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/integration_test.go, storagemarket/testnodes/testnodes.go
Solution to https://github.com/filecoin-project/lotus/issues/7815
=> fix storage provider restart in publish stage

CHANGELOG.md
- refactor: isolate commp in its own package to avoid exposing pulling filecoin-ffi (#659) ([filecoin-project/go-fil-markets#659](https://github.com/filecoin-project/go-fil-markets/pull/659))
Contributors
| dirkmc | 1 | +5/-4 | 3 |
=> release: v1.14.1

CHANGELOG.md
Reverts the following commits:
- log advertisement cid for announcement and update deps (#667) ([filecoin-project/go-fil-markets#667](https://github.com/filecoin-project/go-fil-markets/pull/667))
- release: v1.15.0 ([filecoin-project/go-fil-markets#661](https://github.com/filecoin-project/go-fil-markets/pull/661))
- retrieve by any CID (not just root CID) and reference provider integration (#629) ([filecoin-project/go-fil-markets#629](https://github.com/filecoin-project/go-fil-markets/pull/629))
The revert commit is:
- revert index provider PR #629 and associated PRs (#670) ([filecoin-project/go-fil-markets#670](https://github.com/filecoin-project/go-fil-markets/pull/670))
Contributors
| …
=> release: v1.18.0

CHANGELOG.md
- Update to go-data-transfer v1.14.0 / go-libp2p v0.18.0-rc1 (#669) ([filecoin-project/go-fil-markets#669](https://github.com/filecoin-project/go-fil-markets/pull/669))
Contributors
| Hannah Howard | 1 | +163/-119 | 9 |
| dirkmc | 1 | +20/-0 | 1 |
=> release: v1.19.0

go.mod, go.sum
Upgrade to the latest `index-provider` which includes two main changes:
1. update to go-legs message format
2. cache eviction bug fix
=> Upgrade to `index-provider` `v0.3.0`

storagemarket/impl/provider.go
This PR is removing the `return err` when the markets node fails to connect to the fullnode, as this is not a critical error, and it should not prevent the markets node from booting up.
Relates to:
- https://github.com/filecoin-project/index-provider/issues/177
=> log failure to connect to full node without returning it

storagemarket/impl/provider.go, storagemarket/integration_test.go, storagemarket/provider.go
This is needed so the Boost index provider can lookup legacy deals to serve their CARv2 Index.
=> Lookup state of a deal

retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_test.go
On `retrievalmarket.ErrNotFound`, `answer.Message` is "", which results in a rather obscure error message, namely:
```
retrieval query offer was unavailable:
```
This PR is adding an `answer.Message` so that we get the following error message, and make it clear that the mapping between data cid and piece is missing:
```
retrieval query offer was unavailable: piece info for cid not found (deal has not been added to a piece yet)
```
=> better answer message on ErrNotFound

discovery/impl/local_test.go, go.mod, go.sum, retrievalmarket/impl/provider_test.go, retrievalmarket/migrations/migrations_test.go, shared_testutil/generators.go, storagemarket/impl/client.go, storagemarket/impl/client_test.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/impl/clientutils/clientutils.go, storagemarket/impl/clientutils/clientutils_test.go, storagemarket/impl/provider_test.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/impl/providerutils/providerutils.go, storagemarket/impl/providerutils/providerutils_test.go, storagemarket/impl/requestvalidation/request_validation_test.go, storagemarket/migrations/migrations.go, storagemarket/migrations/migrations_cbor_gen.go, storagemarket/network/types.go, storagemarket/network/types_cbor_gen.go, storagemarket/nodes.go, storagemarket/testharness/dependencies/dependencies.go, storagemarket/testharness/testharness.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
Integrates [a change to FIP-0027](https://github.com/filecoin-project/FIPs/pull/318). o
=> FIP 0027 integration

storagemarket/impl/client.go
close the ask/dealstatus stream, which will cause libp2p resouce resource over limit
=> fix:close ask/dealstatus stream

go.mod, go.sum
Ref: #639
Ref: https://github.com/ipld/go-car/issues/254
Backstory: once upon a time, go-car had a branch that was used here to act as a filestore, but that branch was never merged to master. Over time, go-fil-markets evolved away from that particular usage of go-car, eventually making it disappear entirely in favour of go-car/v2.
https://github.com/ipld/go-car/issues/254 documents attempts to get rid of this branch for good.
#639 was a previous attempt to start removing this branch dependency here.
The last update to the go-car dependency here was #653 which just replaced the branch ref with the latest master, which worked fine because by that time the use of the filestore and need for zero==eof was redundant.
So now we're just moving to a tagged version here and ticking off an item back …
=> chore: update go-car dependency

CHANGELOG.md
- Use new go-state-types state accessors (#711) (#719) ([filecoin-project/go-fil-markets#719](https://github.com/filecoin-project/go-fil-markets/pull/719))
- chore: update go-car dependency (#709) ([filecoin-project/go-fil-markets#709](https://github.com/filecoin-project/go-fil-markets/pull/709))
- fix:close ask/dealstatus stream (#710) ([filecoin-project/go-fil-markets#710](https://github.com/filecoin-project/go-fil-markets/pull/710))
- fix: fire storage deal provider ready event after startup completes (#708) ([filecoin-project/go-fil-markets#708](https://github.com/filecoin-project/go-fil-markets/pull/708))
- release: v1.20.3 (#703) ([filecoin-project/go-fil-markets#703](https://github.com/filecoin-project/go-fil-markets/pull/703)) …
=> release: v1.21.0

CHANGELOG.md
- migrate provider deal proposal label to the new format (#721) ([filecoin-project/go-fil-markets#721](https://github.com/filecoin-project/go-fil-markets/pull/721))
Contributors
| dirkmc | 2 | +1517/-58 | 17 |
=> release: v1.22.0

go.mod, go.sum
Upgrade to the latest `go-car` to roll out a fix to the minimum index
width, where it could cause a validation error when CAR data payload
contains identity CIDs with empty data. Perhaps a silly CID;
nevertheless a valid one.
=> Upgrade to `go-car` `2.4.1`

retrievalmarket/impl/provider.go
switch to the ready manager as opposed to raw pubsub for ready in retrieval provider
=>  use ready manager for retrieval provider

CHANGELOG.md
- Update go libp2p v0.21 (#744) ([filecoin-project/go-fil-markets#744](https://github.com/filecoin-project/go-fil-markets/pull/744))
- feat(retrievalmarket): use ready manager (#739) ([filecoin-project/go-fil-markets#739](https://github.com/filecoin-project/go-fil-markets/pull/739))
Contributors
| Marco Munizaga | 1 | +133/-90 | 11 |
| Hannah Howard | 1 | +4/-4 | 1 |
=> release: v1.24.0

go.mod, piecestore/types.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_environments.go, retrievalmarket/impl/provider_test.go, shared_testutil/test_identitycid.go
There are valid cases where a CAR may have an identity CID as its root that is
not represented as a 'block' within the CAR body and therefore isn't indexed
by the dagstore. In this case, we inspect the identity CID content and treat
the query as a query for the intersection of all of the links within the block.
Ref: https://github.com/filecoin-project/boost/pull/715
=> feat: handle retrieval queries for unindexed identity payload CIDs

go.mod, go.sum, stores/filestore.go, stores/rw_bstores.go
Builds on #747 and relies on https://github.com/ipld/go-car/pull/332
This matches historical precedent, without doing this we get CommP failures where
deals are made with intermediate inline CIDs and the client stores them in
the CAR used to make CommP. car.SelectiveCar is the historical way of doing
this.
e.g. https://github.com/filecoin-project/lotus/blob/a843c52e38da13da489cbe6b290ea49b2660b3fb/node/impl/client/client.go#L1405-L1412
More discussion in https://github.com/ipld/go-car/pull/332, and I'll also open a Lotus PR to bring this in and test it there and will link back here from that.
=> fix: store identity CIDs in CARs for online deals

retrievalmarket/impl/client.go
Closes https://github.com/filecoin-project/go-fil-markets/issues/753
Basically it should be the responsibility of the caller to decide which retrievals are redundant
=> feat: Drop active retrieval check

CHANGELOG.md
- feat: add API methods to subscribe to retrieval query and validation events (#765) ([filecoin-project/go-fil-markets#765](https://github.com/filecoin-project/go-fil-markets/pull/765))
Contributors
| dirkmc | 1 | +99/-4 | 4 |
=> release: v1.25.1

go.mod, go.sum, shared_testutil/mockindexprovider.go, storagemarket/impl/provider.go
Upgrade to the latest index-provider library; note that the library is moved to `ipni` GitHub org and its go module is renamed, replacing `filecoin-project` with `ipni`.
=> Upgrade to the latest index-provider `v.10.0`

piecestore/impl/piecestore.go, piecestore/impl/piecestore_test.go, piecestore/types.go, shared_testutil/test_piecestore.go, storagemarket/impl/providerstates/provider_states.go
For boost's piece store, we need a way to map between the the deal and the piece info.
So pass the deal proposal cid to AddDealForPiece
=> add proposal cid parameter to PieceStore.AddDealForPiece

CHANGELOG.md
- refactor: add proposal cid parameter to PieceStore.AddDealForPiece (#768) ([filecoin-project/go-fil-markets#768](https://github.com/filecoin-project/go-fil-markets/pull/768))
Contributors
| dirkmc | 1 | +8/-7 | 5 |
=> release: v1.26.0

CHANGELOG.md
Generating Changelog for github.com/filecoin-project/go-fil-markets v1.26.1..49cb4a6b647a1fa715d7a114e89534212d617c96
- chore: update dependencoies (#790) ([filecoin-project/go-fil-markets#790](https://github.com/filecoin-project/go-fil-markets/pull/790))
- Chore/use go libipni (#789) ([filecoin-project/go-fil-markets#789](https://github.com/filecoin-project/go-fil-markets/pull/789))
- Data Transfer V2 Integration (#757) ([filecoin-project/go-fil-markets#757](https://github.com/filecoin-project/go-fil-markets/pull/757))
- github.com/hannahhoward/cbor-gen-for (v0.0.0-20200817222906-ea96cece81f1 -> v0.0.0-20230214144701-5d17c9d5243c):
- Optimized "Mode" does not always work ([hannahhoward/cbor-gen-for#2](https://github.com/hannahhoward/cbor-gen-f …
=> release: 1.28.0

shared_testutil/test_network_types.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go
Fix for the errors observed in https://github.com/filecoin-project/lotus/pull/10854
As far as I can tell this is the only place checking deal close errors
=> fix: Ignore stream close error in ProposeDeal
