filecoin-project/go-fil-markets

storagemarket/impl/client_storagemarket.go
Found while reading code. Mostly missed since chan isn't used yet.
=> storagemarket/client: close channel on ListProviders return

storagemarket/impl/provider.go
#oops
We should actually assign our parameters
=> fix(storagemarket): assign net member

storagemarket/impl/provider_states.go
We removed single root cid recording without adding any substitute
=> fix(storagemarket): add back in cid recording

go.mod, go.sum, retrievalmarket/impl/clientstates/client_states_test.go, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/providerstates/provider_states_test.go, retrievalmarket/types.go, retrievalmarket/types_cbor_gen.go, retrievalmarket/types_test.go, shared_testutil/test_types.go
Adds selector to retrieval parameters V1.
Resolves #168
=> Add Selector to retrieval params

.circleci/config.yml, Makefile, go.mod, go.sum
closes #199 
In the Makefile, set up a test target and make the CI config use it instead what it's doing now.
=> Add a test rule to Makefile, use in CI config

CHANGELOG.md, go.mod, go.sum
Merge back transitive dependency upgrade made to spec-actors
=> Master hotfix merge back

go.mod, go.sum, storagemarket/impl/requestvalidation/request_validation_test.go, storagemarket/impl/requestvalidation/types.go, storagemarket/integration_test.go
Update to 0.3.0 of go-data-transfer, fix small breaking changes
=> Update to data transfer with better events

CHANGELOG.md, storagemarket/impl/client.go, storagemarket/impl/provider.go
also remove a couple log messages
=> docs(CHANGELOG): update for 0.2.5 release

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/README.md, storagemarket/impl/clientstates/client_fsm.go, storagemarket/impl/clientstates/client_states.go, storagemarket/impl/clientstates/client_states_test.go, storagemarket/integration_test.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
Implementation of the Market side of issue https://github.com/filecoin-project/go-fil-markets/issues/278:
```
OnDealExpiredOrSlashed(
ctx context.Context,
dealID abi.DealID,
onDealExpired DealExpiredCallback,
onDealSlashed DealSlashedCallback) error
```
=> Storage client - track deals to expiry or slashing

pieceio/pieceio.go, retrievalmarket/doc.go, retrievalmarket/impl/client.go, retrievalmarket/impl/provider.go, retrievalmarket/types.go, storagemarket/dealstatus.go, storagemarket/doc.go, storagemarket/impl/client.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go, storagemarket/types.go
=> Godoc improvements

go.mod, go.sum, storagemarket/impl/client.go
Set the `VerifiedDeal` attribute on a `market.DealProposal`.
Resolves #294
=> Clients can create verified deals

retrievalmarket/types.go
Represent to total cost to retrieve a piece correctly
Add unseal price into total piece retrieval price
=> UnsealPrice should be included in piece retrieval price

retrievalmarket/storage_retrieval_integration_test.go, shared_testutil/generators.go, storagemarket/impl/provider.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/impl/storedask/storedask.go, storagemarket/impl/storedask/storedask_test.go, storagemarket/integration_test.go, storagemarket/provider.go, storagemarket/types.go, storagemarket/types_cbor_gen.go
=> Adding different prices for verified deals

retrievalmarket/impl/provider_environments.go
Should fix https://github.com/filecoin-project/lotus/issues/2765
=> retrieval: Drain piece readers

go.mod, go.sum, retrievalmarket/impl/dtutils/dtutils.go, retrievalmarket/impl/dtutils/dtutils_test.go, storagemarket/impl/dtutils/dtutils.go, storagemarket/impl/dtutils/dtutils_test.go
Update to latest data transfer
Update deps, also includes a specific logging improvement
=> Update data transfer 0.6.1

storagemarket/impl/providerstates/provider_states.go
Need this in https://github.com/filecoin-project/lotus/pull/3350
=> Plumb deal.PublishCid in HandoffDeal

retrievalmarket/network/libp2p_impl.go, storagemarket/network/libp2p_impl.go
Increase retry timeout for connection attempts
=> Increase retry timeout

retrievalmarket/storage_retrieval_integration_test.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/integration_test.go
Enhance storage provider deal validation to more closely match the validations done by the storage market actor.
Resolves filecoin-project/lotus/issues/3865
=> Additional validations for deal proposals

CHANGELOG.md
also reverses changelog order (latest -> oldest)
=> docs(CHANGELOG): update for 0.6.2

retrievalmarket/network/libp2p_impl.go, storagemarket/network/libp2p_impl.go
Just a rebase of https://github.com/filecoin-project/go-fil-markets/pull/429
=> Exponential backoff, rebased

CHANGELOG.md
- fix: clear deal message when deal accepted (#461) ([filecoin-project/go-fil-markets#461](https://github.com/filecoin-project/go-fil-markets/pull/461))
Contributors
| dirkmc | 2 | +24/-0 | 2 |
=> release: v1.0.9

storagemarket/impl/provider.go
This helps resolve the issues of getting tons of EOFs when trying to check on my deal
=> always try to return some message to the client

CHANGELOG.md
Generating Changelog for github.com/filecoin-project/go-fil-markets v1.2.2..cf830ee0459221d4ba7e91f105a0f19b6d5a453e
- fix: process payment request from provider while initiating payment channel (#520) ([filecoin-project/go-fil-markets#520](https://github.com/filecoin-project/go-fil-markets/pull/520))
- fix: remove LocatePieceForDealWithinSector (no longer used) (#518) ([filecoin-project/go-fil-markets#518](https://github.com/filecoin-project/go-fil-markets/pull/518))
Contributors
| dirkmc | 3 | +66/-60 | 8 |
=> release: v1.2.3

CHANGELOG.md
Adds Dynamic Retrieval Pricing
- Dynamic Retrieval Pricing (#542) ([filecoin-project/go-fil-markets#542](https://github.com/filecoin-project/go-fil-markets/pull/542))
Contributors
| Aarsh Shah | 1 | +1224/-130 | 17 |
| dirkmc | 1 | +18/-0 | 1 |
=> release: v1.5.0

CHANGELOG.md, retrievalmarket/impl/integration_test.go, retrievalmarket/impl/provider.go, retrievalmarket/impl/provider_environments.go, retrievalmarket/impl/provider_test.go, retrievalmarket/impl/providerstates/provider_states.go, retrievalmarket/impl/providerstates/provider_states_test.go, retrievalmarket/impl/requestvalidation/requestvalidation.go, retrievalmarket/impl/requestvalidation/requestvalidation_test.go, retrievalmarket/impl/testnodes/test_retrieval_provider_node.go, retrievalmarket/network/network.go, retrievalmarket/network/old_query_stream.go, retrievalmarket/network/query_stream.go, retrievalmarket/nodes.go, retrievalmarket/storage_retrieval_integration_test.go, retrievalmarket/types.go, retrievalmarket/types_test.go, shared_testutil/test_network_types.go
@hannahhoward udpating your branch with latest release so lotus can be built
Reference: https://github.com/filecoin-project/lotus/pull/6393/commits/70114b604349d60e1aa6c2f5dff2edb766cf7401#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R37-R39
=> Feat/update update graphsync v0.8.0 to 1.5.0

dagstore/dagstorewrapper.go, go.mod, go.sum, retrievalmarket/impl/integration_test.go, retrievalmarket/storage_retrieval_integration_test.go
@dirkmc As discussed yesterday.
=> Attempt to register and acquire a shard again during Loading if the first attempt fails with `ErrShardUnknown`

docs/storageprovider.mmd, storagemarket/events.go
These are showing empty in the journals.
=> add missing event labels.

retrievalmarket/impl/client.go, retrievalmarket/impl/dtutils/dtutils.go, retrievalmarket/impl/provider.go, storagemarket/impl/client.go, storagemarket/impl/dtutils/dtutils.go, storagemarket/impl/provider.go
Improve logging
- log processing of event listeners -- all clients and providers -- debug
- log processing of data transfer events -- all clients and providers - debug
=> feat(logging): add various logging events

piecestore/impl/piecestore.go, piecestore/impl/piecestore_test.go
On retrieval of an unrecognized payload CID, return a nice not found error instead of something like "No state for /Qmd8VJwP745eE5xsmvbW56ZuAoQvXDhrZ9evpkNBk5eXiV"
=> fix retrieval not found error

shared/commp.go, shared/inflator_reader.go, shared/inflator_reader_test.go, storagemarket/impl/provider.go, storagemarket/impl/provider_environments.go, storagemarket/impl/providerstates/provider_states.go, storagemarket/impl/providerstates/provider_states_test.go, storagemarket/integration_test.go, storagemarket/nodes.go, storagemarket/testnodes/testnodes.go
So we can seek back to the start when retrying AddPiece
=> add SeekStart method to inflator reader

CHANGELOG.md
- add SeekStart method to inflator reader (#656) ([filecoin-project/go-fil-markets#656](https://github.com/filecoin-project/go-fil-markets/pull/656))
Contributors
| dirkmc | 1 | +317/-52 | 10 |
=> release: v1.14.0

CHANGELOG.md
Update change logs in preparation for `v1.20.0` release.
=> release: v1.20.0

CHANGELOG.md
Update Changelog and make a release
=> release: v1.20.1

shared_testutil/mockdagstorewrapper.go, storagemarket/impl/clientutils/clientutils_test.go, stores/dagstore.go
Part of https://github.com/filecoin-project/lotus/issues/9009
=> feat: dagstore_wrapper: DestroyShardSync

retrievalmarket/provider.go
Per https://github.com/filecoin-project/boost/pull/707#issuecomment-1232667552, as an alternative to https://github.com/filecoin-project/go-fil-markets/pull/699, this simply exposes the GetDynamicAsk method. The remainder of that PR will take place inside boost.
=> Expose GetDynamicAsk

CHANGELOG.md
Release latest changes to index-provider dependencies in preparation for roll up to lotus.
=> release: v1.25.3

go.mod, go.sum, retrievalmarket/impl/dtutils/dtutils.go, retrievalmarket/impl/dtutils/dtutils_test.go, shared_testutil/test_datatransfer.go, storagemarket/impl/dtutils/dtutils.go, storagemarket/impl/dtutils/dtutils_test.go
companion for https://github.com/filecoin-project/go-data-transfer/pull/362
=> Update for new data transfer configuration interface
